name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 设置 JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: 验证核心类文件存在
      run: |
        if [ -f "core/interfaces/src/main/kotlin/app/aaps/core/interfaces/rx/events/EventOverviewBolusProgress.kt" ]; then
          echo "✅ 找到 EventOverviewBolusProgress.kt"
          cat "core/interfaces/src/main/kotlin/app/aaps/core/interfaces/rx/events/EventOverviewBolusProgress.kt"
        else
          echo "❌ 未找到核心类文件"
          exit 1
        fi

    - name: 授予 gradlew 执行权限
      run: chmod +x gradlew

    - name: 彻底清理缓存
      run: |
        ./gradlew clean
        rm -rf ~/.gradle/caches/
        rm -rf core/interfaces/build/
        rm -rf pump/danar/build/

    - name: 构建 core:interfaces（确保编译成功）
      run: ./gradlew :core:interfaces:assembleFullRelease --stacktrace

    - name: 检查 core:interfaces 编译产物
      run: |
        find core/interfaces/build/intermediates/classes/fullRelease/ -name "EventOverviewBolusProgress.class"
        if [ $? -ne 0 ]; then
          echo "❌ core:interfaces 未生成目标类"
          exit 1
        fi

    - name: 构建 pump:danar
      run: |
        export storePassword=${{ secrets.STORE_PASSWORD }}
        export keyAlias=${{ secrets.KEY_ALIAS }}
        export keyPassword=${{ secrets.KEY_PASSWORD }}
        export storeFile=${{ secrets.STORE_FILE }}
        ./gradlew :pump:danar:assembleFullRelease --stacktrace

    - name: 归档产物
      uses: actions/upload-artifact@v4
      with:
        name: danar-release
        path: pump/danar/build/outputs/aar/
