name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Clean all caches (彻底清理)
      run: |
        ./gradlew clean
        rm -rf ~/.gradle/caches/
        rm -rf ~/.gradle/daemon/
        rm -rf core/interfaces/build/
        rm -rf pump/danar/build/
    
    - name: Build core:interfaces (强制编译并输出结果)
      run: |
        ./gradlew :core:interfaces:assembleDebug --stacktrace
        # 检查 core:interfaces 的构建产物是否存在
        ls -l core/interfaces/build/libs/
    
    - name: Build pump:danar (依赖已编译的 core:interfaces)
      run: |
        export storePassword=${{ secrets.STORE_PASSWORD }}
        export keyAlias=${{ secrets.KEY_ALIAS }}
        export keyPassword=${{ secrets.KEY_PASSWORD }}
        export storeFile=${{ secrets.STORE_FILE }}
        ./gradlew :pump:danar:assembleFullRelease --stacktrace
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aaps
        path: app/build/outputs/apk/full/release
